[package]
name = "podcastersctl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive", "unstable-markdown"] }

[lints]
workspace = true

[dev-dependencies]
assert_cmd = { version = "2.2.2", features = ["color", "color-auto"] }
predicates = "3.1.4"
rstest = "0.26.1"
