application:
  port: 8125

mongo:
 uri: ""
 db: "personal_blog"
 collection: "Podcast"
 require_auth: true
 pool_size: 1
 connection_timeout: 1

redis:
  uri: ""
  key: "podcast:"
  pool_size: 1
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

