[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { version = "4.14.1", optional = true }
actix-files = { version = "0.6.10", optional = true}
leptos = { version = "0.8", default-features = false, features = ["hydrate", "ssr"] }
leptos_actix = { version = "0.8", optional = true }
leptos_meta = { version = "0.8.6", default-features = false }
leptos_router = { version = "0.8", default-features = false }
frontend = { path = "../frontend" }
mongodb = "3.8.0"
rand = "0.10.2"
redis = { version = "1.6.0", features = ["aio", "connection-manager", "tokio-comp"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
anyhow = "1.0.104"
config = "0.15.25"
models = { version = "0.1.0", path = "../models" }
serde = "1.0.229"
serde_json = "1.0.151"
futures = "0.3.34"
base64 = "0.23.1"
chacha20 = "0.10.1"
hex = "0.4.3"
dotenvy = "0.15.7"

[features]
ssr = [
  "dep:actix-files",
  "dep:leptos_actix",
  "dep:actix-web",
  "dep:leptos_actix",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "frontend/ssr",
]
