application:
  protocol: https
  host: 0.0.0.0
  base_url: "http://0.0.0.0"

debug: false

secret:
  secret_key: ""
  token_expiration: 30
  hmac_secret: ""
      
frontend_url: "http://sundaylifeservices.com"
